---
- name: "03. Configuración de MariaDB"
  hosts: db-tfg
  become: yes
  tasks:
    - name: "Instalar MariaDB Server y dependencias"
      ansible.builtin.apt:
        name: 
          - mariadb-server
          - python3-pymysql
        state: present
        update_cache: yes

    - name: "Asegurar que MariaDB esté en ejecución"
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: "Crear la base de datos necesaria"
      community.mysql.mysql_db:
        name: tfg_database
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: "Configurar acceso remoto"
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Reiniciar MariaDB

    - name: "Crear usuario para la WebApp"
      community.mysql.mysql_user:
        name: "tfg_user"
        password: "tfg_password_2026"
        priv: "tfg_database.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: "Crear tabla activos e insertar datos de red"
      community.mysql.mysql_query:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_db: tfg_database
        query:
          - "CREATE TABLE IF NOT EXISTS activos (id INT AUTO_INCREMENT PRIMARY KEY, nombre_servidor VARCHAR(255), direccion_ip VARCHAR(15), puerto INT);"
          - "INSERT IGNORE INTO activos (id, nombre_servidor, direccion_ip, puerto) VALUES (1, 'Proxy Nginx', '192.168.1.60', 80), (2, 'App Flask', '192.168.1.61', 8000), (3, 'DB MariaDB', '192.168.1.62', 3306), (4, 'Nodo Cloud GCP', '100.66.16.119', 22);"
  handlers:
    - name: Reiniciar MariaDB
      ansible.builtin.service:
        name: mariadb
        state: restarted