---
- name: "07. Despliegue de la Aplicacion"
  hosts: webapp-tfg
  become: yes
  tasks:
    - name: "Crear directorios necesarios"
      ansible.builtin.file:
        path: /opt/tfg_app/templates
        state: directory
        mode: '0755'

    - name: "Copiar archivos de la app al contenedor"
      ansible.builtin.copy:
        src: "../../flask_app/{{ item }}"
        dest: "/opt/tfg_app/{{ item }}"
      loop:
        - app.py
        - templates/index.html
        - requirements.txt

    - name: "Inyectar variables reales en app.py"
      ansible.builtin.replace:
        path: /opt/tfg_app/app.py
        regexp: "{{ item.buscar }}"
        replace: "{{ item.poner }}"
      loop:
        - { buscar: "DB_IP_PLACEHOLDER", poner: "{{ db_ip }}" }
        - { buscar: "DB_USER_PLACEHOLDER", poner: "{{ db_user }}" }
        - { buscar: "DB_PASS_PLACEHOLDER", poner: "{{ db_pass }}" }
        - { buscar: "DB_NAME_PLACEHOLDER", poner: "{{ db_name }}" }

    - name: "Configurar entorno virtual y dependencias"
      ansible.builtin.pip:
        requirements: /opt/tfg_app/requirements.txt
        virtualenv: /opt/tfg_app/venv
        virtualenv_command: python3 -m venv

    - name: "Crear servicio del sistema"
      ansible.builtin.copy:
        dest: /etc/systemd/system/tfg-app.service
        content: |
          [Unit]
          Description=Servidor Flask TFG
          After=network.target

          [Service]
          User=root
          WorkingDirectory=/opt/tfg_app
          ExecStart=/opt/tfg_app/venv/bin/python3 /opt/tfg_app/app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: "Iniciar y habilitar la aplicacion"
      ansible.builtin.systemd:
        name: tfg-app
        state: restarted
        enabled: yes
        daemon_reload: yes