---
- name: "10. Instalacion de Monitorizacion (Netdata)"
  hosts: lxc_containers
  become: yes

  tasks:
    - name: "Descargar e instalar Netdata mediante script oficial"
      ansible.builtin.shell: |
        wget -O /tmp/netdata-kickstart.sh https://get.netdata.cloud/kickstart.sh
        sh /tmp/netdata-kickstart.sh --non-interactive
      args:
        creates: /usr/sbin/netdata

    - name: "Crear directorio de override para Netdata"
      ansible.builtin.file:
        path: /etc/systemd/system/netdata.service.d
        state: directory
        mode: '0755'

    - name: "Aplicar configuracion de compatibilidad LXC (Evitar error 226/NAMESPACE)"
      ansible.builtin.copy:
        dest: /etc/systemd/system/netdata.service.d/override.conf
        content: |
          [Service]
          ProtectSystem=no
          ProtectHome=no
          PrivateTmp=no

    - name: "Asegurar que el servicio Netdata este activo y con la nueva configuracion"
      ansible.builtin.systemd:
        name: netdata
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: "Abrir puerto de Netdata en el Firewall (19999)"
      community.general.ufw:
        rule: allow
        port: '19999'
        proto: tcp