---
- name: "03. Configuración de MariaDB"
  hosts: db-tfg
  become: yes
  tasks:
    - name: "Instalar MariaDB Server y dependencias de Python"
      ansible.builtin.apt:
        name: 
          - mariadb-server
          - python3-pymysql
        state: present
        update_cache: yes

    - name: "Asegurar que MariaDB esté en ejecución"
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: "Configurar MariaDB para escuchar en todas las interfaces"
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Reiniciar MariaDB

    - name: "Crear usuario para la WebApp con acceso remoto"
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "*.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

  handlers:
    - name: Reiniciar MariaDB
      ansible.builtin.service:
        name: mariadb
        state: restarted