---
- name: "03. Configuraci√≥n Avanzada de Base de Datos"
  hosts: db-tfg
  become: yes
  vars:
    db_name: "tfg_database"
    db_user: "tfg_user"
    db_pass: "tfg_password_2026" # Cambia esto si quieres
    webapp_ip: "192.168.1.61"

  tasks:
    - name: "Instalar dependencias de Python para MySQL"
      ansible.builtin.apt:
        name: python3-pymysql
        state: present

    - name: "Configurar MariaDB para escuchar en todas las interfaces"
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Reiniciar MariaDB

    - name: "Crear la base de datos del TFG"
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: "Crear usuario de base de datos para la WebApp"
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "{{ db_name }}.*:ALL"
        host: "{{ webapp_ip }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

  handlers:
    - name: Reiniciar MariaDB
      ansible.builtin.service:
        name: mariadb
        state: restarted